create table `order` (
    orderId VARCHAR(200),
    sequence VARCHAR(200),
    marketplaceOrderId VARCHAR(200),
    marketplaceServicesEndpoint VARCHAR(200),
    sellerOrderId VARCHAR(200),
    origin VARCHAR(200),
    afffiliateId VARCHAR(200),
    salesChannel VARCHAR(200),
    merchantName VARCHAR(200),
    status VARCHAR(200),
    statusDescription VARCHAR(200),
    value VARCHAR(200),
    creationDate timestamp,
    lastChange timestamp,
    orderGroup VARCHAR(200),
    giftRegistryData VARCHAR(200),
    marketingData VARCHAR(200),
    callCenterOperatorData VARCHAR(200),
    followUpEmail VARCHAR(200),
    hostname VARCHAR(200),
    roundingError VARCHAR(200),
    orderFormId VARCHAR(200),
    commercialConditionData VARCHAR(200),
    isCompleted VARCHAR(200),
    allowCancellation VARCHAR(200),
    allowEdition VARCHAR(200),
    isCheckedIn VARCHAR(200),
    authorizedDate timestamp,
    invoicedDate timestamp,
    cancelReason VARCHAR(200),
    clientProfileData_id VARCHAR(200),
    clientProfileData_email VARCHAR(200),
    clientProfileData_firstName VARCHAR(200),
    clientProfileData_lastName VARCHAR(200),
    clientProfileData_documentType VARCHAR(200),
    clientProfileData_document VARCHAR(200),
    clientProfileData_phone VARCHAR(200),
    clientProfileData_corporateName VARCHAR(200),
    clientProfileData_tradeName VARCHAR(200),
    clientProfileData_corporateDocument VARCHAR(200),
    clientProfileData_stateInscription VARCHAR(200),
    clientProfileData_corporatePhone VARCHAR(200),
    clientProfileData_isCorporate VARCHAR(200),
    clientProfileData_userProfileId VARCHAR(200),
    clientProfileData_customerClass VARCHAR(200),
    marketingData_id VARCHAR(200),
    marketingData_utmSource VARCHAR(200),
    marketingData_utmPartner VARCHAR(200),
    marketingData_utmMedium VARCHAR(200),
    marketingData_coupon VARCHAR(200),
    marketingData_utmiCampaign VARCHAR(200),
    marketingData_utmipage VARCHAR(200),
    marketingData_utmiPart VARCHAR(200),
    ratesAndBenefitsData_id VARCHAR(200),
    shippingData_id VARCHAR(200),
    shippingData_address_addressType VARCHAR(200),
    shippingData_address_receiverName VARCHAR(200),
    shippingData_address_addressId VARCHAR(200),
    shippingData_address_postalCode VARCHAR(200),
    shippingData_address_city VARCHAR(200),
    shippingData_address_state VARCHAR(200),
    shippingData_address_country VARCHAR(200),
    shippingData_address_street VARCHAR(200),
    shippingData_address_number VARCHAR(200),
    shippingData_address_neighborhood VARCHAR(200),
    shippingData_address_complement VARCHAR(500),
    shippingData_address_reference VARCHAR(500),
    storePreferencesData_countryCode VARCHAR(200),
    storePreferencesData_currencyCode VARCHAR(200),
    storePreferencesData_currencyLocale VARCHAR(200),
    storePreferencesData_currencySymbol VARCHAR(200),
    storePreferencesData_timeZone VARCHAR(200),
    storePreferencesData_currencyFormatInfo_CurrencyDecimalDigits VARCHAR(200),
    storePreferencesData_currencyFormatInfo_CurrencyDecimalSeparator VARCHAR(200),
    storePreferencesData_currencyFormatInfo_CurrencyGroupSeparator VARCHAR(200),
    storePreferencesData_currencyFormatInfo_CurrencyGroupSize VARCHAR(200),
    storePreferencesData_currencyFormatInfo_StartsWithCurrencySymbol VARCHAR(200),
    marketplace_baseURL VARCHAR(200),
    marketplace_isCertified VARCHAR(200),
    marketplace_name VARCHAR(200),
    openTextField_value VARCHAR(200),
    primary key (orderId)
);

create table items (
    uniqueId VARCHAR(200),
    id VARCHAR(200),
    productId VARCHAR(200),
    ean VARCHAR(200),
    lockId VARCHAR(200),
    quantity VARCHAR(200),
    seller VARCHAR(200),
    name VARCHAR(200),
    refId VARCHAR(200),
    price VARCHAR(200),
    listPrice VARCHAR(200),
    manualPrice VARCHAR(200),
    sellerSku VARCHAR(200),
    priceValidUntil VARCHAR(200),
    commission VARCHAR(200),
    tax VARCHAR(200),
    preSaleDate timestamp,
    measurementUnit VARCHAR(200),
    unitMultiplier VARCHAR(200),
    sellingPrice VARCHAR(200),
    isGift VARCHAR(200),
    shippingPrice VARCHAR(200),
    rewardValue VARCHAR(200),
    freightCommission VARCHAR(200),
    taxCode VARCHAR(200),
    parentItemIndex VARCHAR(200),
    parentAssemblyBinding VARCHAR(200),
    callCenterOperator VARCHAR(200),
    serialNumbers VARCHAR(200),
    costPrice VARCHAR(200),
    orderId VARCHAR(200),
    primary key (uniqueId, orderId),
    foreign key (orderId) references `order`(orderId) ON UPDATE CASCADE ON DELETE CASCADE
);

create table totals (
    id VARCHAR(200),
    name VARCHAR(200),
    value VARCHAR(200),
    orderId VARCHAR(200),
    primary key (id, orderId),
    foreign key (orderId) references `order`(orderId) ON UPDATE CASCADE ON DELETE CASCADE
);

create table sellers (
    id VARCHAR(200),
    name VARCHAR(200),
    logo VARCHAR(200),
    fulfillmentEndpoint VARCHAR(200),
    orderId VARCHAR(200),
    primary key (id, orderId),
    foreign key (orderId) references `order`(orderId) ON UPDATE CASCADE ON DELETE CASCADE
);

create table itemsMetadata (
    Id VARCHAR(200),
    Seller VARCHAR(200),
    Name VARCHAR(200),
    SkuName VARCHAR(200),
    ProductId VARCHAR(200),
    RefId VARCHAR(200),
    Ean VARCHAR(200),
    orderId VARCHAR(200),
    primary key (id, orderId),
    foreign key (orderId) references `order`(orderId) ON UPDATE CASCADE ON DELETE CASCADE
);

create table paymentData_transactions_payments (
    id VARCHAR(200),
    paymentSystem VARCHAR(200),
    paymentSystemName VARCHAR(200),
    value integer,
    installments integer,
    referenceValue integer,
    orderId VARCHAR(200),
    primary key (id, paymentSystem, orderId),
    foreign key (orderId) references `order`(orderId) ON UPDATE CASCADE ON DELETE CASCADE
);
