create table "order" (
    orderId TEXT,
    sequence TEXT,
    marketplaceOrderId TEXT,
    marketplaceServicesEndpoint TEXT,
    sellerOrderId TEXT,
    origin TEXT,
    afffiliateId TEXT,
    salesChannel TEXT,
    merchantName TEXT,
    status TEXT,
    statusDescription TEXT,
    value TEXT,
    creationDate timestamptz,
    lastChange timestamptz,
    orderGroup TEXT,
    giftRegistryData TEXT,
    marketingData TEXT,
    callCenterOperatorData TEXT,
    followUpEmail TEXT,
    hostname TEXT,
    roundingError TEXT,
    orderFormId TEXT,
    commercialConditionData TEXT,
    isCompleted TEXT,
    allowCancellation TEXT,
    allowEdition TEXT,
    isCheckedIn TEXT,
    authorizedDate timestamptz,
    invoicedDate timestamptz,
    cancelReason TEXT,
    clientProfileData_id TEXT,
    clientProfileData_email TEXT,
    clientProfileData_firstName TEXT,
    clientProfileData_lastName TEXT,
    clientProfileData_documentType TEXT,
    clientProfileData_document TEXT,
    clientProfileData_phone TEXT,
    clientProfileData_corporateName TEXT,
    clientProfileData_tradeName TEXT,
    clientProfileData_corporateDocument TEXT,
    clientProfileData_stateInscription TEXT,
    clientProfileData_corporatePhone TEXT,
    clientProfileData_isCorporate TEXT,
    clientProfileData_userProfileId TEXT,
    clientProfileData_customerClass TEXT,
    marketingData_id TEXT,
    marketingData_utmSource TEXT,
    marketingData_utmPartner TEXT,
    marketingData_utmMedium TEXT,
    marketingData_coupon TEXT,
    marketingData_utmiCampaign TEXT,
    marketingData_utmipage TEXT,
    marketingData_utmiPart TEXT,
    ratesAndBenefitsData_id TEXT,
    shippingData_id TEXT,
    shippingData_address_addressType TEXT,
    shippingData_address_receiverName TEXT,
    shippingData_address_addressId TEXT,
    shippingData_address_postalCode TEXT,
    shippingData_address_city TEXT,
    shippingData_address_state TEXT,
    shippingData_address_country TEXT,
    shippingData_address_street TEXT,
    shippingData_address_number TEXT,
    shippingData_address_neighborhood TEXT,
    shippingData_address_complement TEXT,
    shippingData_address_reference TEXT,
    storePreferencesData_countryCode TEXT,
    storePreferencesData_currencyCode TEXT,
    storePreferencesData_currencyLocale TEXT,
    storePreferencesData_currencySymbol TEXT,
    storePreferencesData_timeZone TEXT,
    storePreferencesData_currencyFormatInfo_CurrencyDecimalDigits TEXT,
    storePreferencesData_currencyFormatInfo_CurrencyDecimalSeparator TEXT,
    storePreferencesData_currencyFormatInfo_CurrencyGroupSeparator TEXT,
    storePreferencesData_currencyFormatInfo_CurrencyGroupSize TEXT,
    storePreferencesData_currencyFormatInfo_StartsWithCurrencySymbol TEXT,
    marketplace_baseURL TEXT,
    marketplace_isCertified TEXT,
    marketplace_name TEXT,
    primary key (orderId)
);

create table "items" (
    uniqueId TEXT,
    id TEXT,
    productId TEXT,
    ean TEXT,
    lockId TEXT,
    quantity TEXT,
    seller TEXT,
    name TEXT,
    refId TEXT,
    price TEXT,
    listPrice TEXT,
    manualPrice TEXT,
    sellerSku TEXT,
    priceValidUntil TEXT,
    commission TEXT,
    tax TEXT,
    preSaleDate timestamptz,
    measurementUnit TEXT,
    unitMultiplier TEXT,
    sellingPrice TEXT,
    isGift TEXT,
    shippingPrice TEXT,
    rewardValue TEXT,
    freightCommission TEXT,
    priceDefinitions TEXT,
    taxCode TEXT,
    parentItemIndex TEXT,
    parentAssemblyBinding TEXT,
    callCenterOperator TEXT,
    serialNumbers TEXT,
    costPrice TEXT,
    orderId TEXT,
    primary key (uniqueId, orderId),
    foreign key (orderId) references "order"(orderId)
);

create table "totals" (
    id TEXT,
    name TEXT,
    value TEXT,
    orderId TEXT,
    primary key (id, orderId),
    foreign key (orderId) references "order"(orderId)
);

create table "sellers" (
    id TEXT,
    name TEXT,
    logo TEXT,
    fulfillmentEndpoint TEXT,
    orderId TEXT,
    primary key (id, orderId),
    foreign key (orderId) references "order"(orderId)
);

create table "itemsMetadata" (
    Id TEXT,
    Seller TEXT,
    Name TEXT,
    SkuName TEXT,
    ProductId TEXT,
    RefId TEXT,
    Ean TEXT,
    orderId TEXT,
    primary key (id, orderId),
    foreign key (orderId) references "order"(orderId)
);

--create table "rateAndBenefitsIdentifiers" (
--    description TEXT,
--    featured TEXT,
--    id TEXT,
--    name TEXT,
--    additionalInfo TEXT,
--    matchedParameters_brandCatalogSystem TEXT,
--    matchedParameters_productCatalogSystem TEXT,
--    matchedParameters_paymentMethodId TEXT,
--    orderId TEXT
--)

