exemplo_get_order = {
    "emailTracked": "a27499cad31f42b7a771ae34f57c8358@ct.vtex.com.br",
    "approvedBy": None,
    "cancelledBy": None,
    "cancelReason": None,
    "orderId": "v5195004lux-01",
    "sequence": "502556",
    "marketplaceOrderId": "",
    "marketplaceServicesEndpoint": "http://oms.vtexinternal.com.br/api/oms?an=luxstore",
    "sellerOrderId": "00-v5195004lux-01",
    "origin": "Marketplace",
    "affiliateId": "",
    "salesChannel": "1",
    "merchantName": None,
    "status": "handling",
    "statusDescription": "Preparando Entrega",
    "value": 1160,
    "creationDate": "2019-01-28T20:09:43.8999580+00:00",
    "lastChange": "2019-02-06T20:46:11.7010747+00:00",
    "orderGroup": None,
    "totals": [
        {
            "id": "Items",
            "name": "Total dos Itens",
            "value": 3290
        },
        {
            "id": "Discounts",
            "name": "Total dos Descontos",
            "value": 0
        },
        {
            "id": "Shipping",
            "name": "Total do Frete",
            "value": 1160
        },
        {
            "id": "Tax",
            "name": "Total da Taxa",
            "value": 0
        },
        {
            "id": "Change",
            "name": "Total das mudanças",
            "value": -3290
        }
    ],
    "items": [
        {
            "uniqueId": "87F0945396994B349158C7D9C9941442",
            "id": "1234568358",
            "productId": "9429485",
            "ean": None,
            "lockId": "00-v5195004lux-01",
            "itemAttachment": {
                "content": {},
                "name": None
            },
            "attachments": [],
            "quantity": 1,
            "seller": "1",
            "name": "Bay Max L",
            "refId": "BIGHEROBML",
            "price": 3290,
            "listPrice": 3290,
            "manualPrice": None,
            "priceTags": [],
            "imageUrl": "http://luxstore.vteximg.com.br/arquivos/ids/159263-55-55/image-cc1aed75cbfa424a85a94900be3eacec.jpg?v=636795432619830000",
            "detailUrl": "/bay-max-9429485/p",
            "components": [],
            "bundleItems": [],
            "params": [],
            "offerings": [],
            "sellerSku": "1234568358",
            "priceValidUntil": None,
            "commission": 0,
            "tax": 0,
            "preSaleDate": None,
            "additionalInfo": {
                "brandName": "VTEX",
                "brandId": "2000023",
                "categoriesIds": "/1/",
                "productClusterId": "135,142",
                "commercialConditionId": "5",
                "dimension": {
                    "cubicweight": 0.7031,
                    "height": 15,
                    "length": 15,
                    "weight": 15,
                    "width": 15
                },
                "offeringInfo": None,
                "offeringType": None,
                "offeringTypeId": None
            },
            "measurementUnit": "un",
            "unitMultiplier": 1,
            "sellingPrice": 3290,
            "isGift": False,
            "shippingPrice": None,
            "rewardValue": 0,
            "freightCommission": 0,
            "priceDefinitions": None,
            "taxCode": None,
            "parentItemIndex": None,
            "parentAssemblyBinding": None
        }
    ],
    "marketplaceItems": [],
    "clientProfileData": {
        "id": "clientProfileData",
        "email": "rodrigo.cunha@vtex.com.br",
        "firstName": "Rodrigo",
        "lastName": "VTEX",
        "documentType": "cpf",
        "document": "11047867702",
        "phone": "+5521972321094",
        "corporateName": None,
        "tradeName": None,
        "corporateDocument": None,
        "stateInscription": None,
        "corporatePhone": None,
        "isCorporate": False,
        "userProfileId": "5a3692de-358a-4bea-8885-044bce33bb93",
        "customerClass": None
    },
    "giftRegistryData": None,
    "marketingData": None,
    "ratesAndBenefitsData": {
        "id": "ratesAndBenefitsData",
        "rateAndBenefitsIdentifiers": []
    },
    "shippingData": {
        "id": "shippingData",
        "address": {
            "addressType": "residential",
            "receiverName": "Rodrigo Cunha",
            "addressId": "-1425945657910",
            "postalCode": "22250-040",
            "city": "Rio de Janeiro",
            "state": "RJ",
            "country": "BRA",
            "street": "Praia de Botafogo",
            "number": "300",
            "neighborhood": "Botafogo",
            "complement": "3",
            "reference": None,
            "geoCoordinates": []
        },
        "logisticsInfo": [
            {
                "itemIndex": 0,
                "selectedSla": "Normal",
                "lockTTL": "10d",
                "price": 1160,
                "listPrice": 1160,
                "sellingPrice": 1160,
                "deliveryWindow": None,
                "deliveryCompany": "Todos os CEPS",
                "shippingEstimate": "5bd",
                "shippingEstimateDate": "2019-02-04T20:33:46.4595004+00:00",
                "slas": [
                    {
                        "id": "Normal",
                        "name": "Normal",
                        "shippingEstimate": "5bd",
                        "deliveryWindow": None,
                        "price": 1160,
                        "deliveryChannel": "delivery",
                        "pickupStoreInfo": {
                            "additionalInfo": None,
                            "address": None,
                            "dockId": None,
                            "friendlyName": None,
                            "isPickupStore": False
                        },
                        "polygonName": None
                    },
                    {
                        "id": "Expressa",
                        "name": "Expressa",
                        "shippingEstimate": "5bd",
                        "deliveryWindow": None,
                        "price": 1160,
                        "deliveryChannel": "delivery",
                        "pickupStoreInfo": {
                            "additionalInfo": None,
                            "address": None,
                            "dockId": None,
                            "friendlyName": None,
                            "isPickupStore": False
                        },
                        "polygonName": None
                    },
                    {
                        "id": "Quebra Kit",
                        "name": "Quebra Kit",
                        "shippingEstimate": "2bd",
                        "deliveryWindow": None,
                        "price": 1392,
                        "deliveryChannel": "delivery",
                        "pickupStoreInfo": {
                            "additionalInfo": None,
                            "address": None,
                            "dockId": None,
                            "friendlyName": None,
                            "isPickupStore": False
                        },
                        "polygonName": None
                    },
                    {
                        "id": "Sob Encomenda",
                        "name": "Sob Encomenda",
                        "shippingEstimate": "32bd",
                        "deliveryWindow": None,
                        "price": 1392,
                        "deliveryChannel": "delivery",
                        "pickupStoreInfo": {
                            "additionalInfo": None,
                            "address": None,
                            "dockId": None,
                            "friendlyName": None,
                            "isPickupStore": False
                        },
                        "polygonName": None
                    }
                ],
                "shipsTo": [
                    "BRA"
                ],
                "deliveryIds": [
                    {
                        "courierId": "197a56f",
                        "courierName": "Todos os CEPS",
                        "dockId": "1",
                        "quantity": 1,
                        "warehouseId": "1_1"
                    }
                ],
                "deliveryChannel": "delivery",
                "pickupStoreInfo": {
                    "additionalInfo": None,
                    "address": None,
                    "dockId": None,
                    "friendlyName": None,
                    "isPickupStore": False
                },
                "addressId": "-1425945657910",
                "polygonName": None
            }
        ],
        "trackingHints": None,
        "selectedAddresses": [
            {
                "addressId": "-1425945657910",
                "addressType": "residential",
                "receiverName": "Rodrigo Cunha",
                "street": "Praia de Botafogo",
                "number": "518",
                "complement": "10",
                "neighborhood": "Botafogo",
                "postalCode": "22250-040",
                "city": "Rio de Janeiro",
                "state": "RJ",
                "country": "BRA",
                "reference": None,
                "geoCoordinates": []
            }
        ]
    },
    "paymentData": {
        "transactions": [
            {
                "isActive": True,
                "transactionId": "418213DE29634837A63DD693A937A696",
                "merchantName": "luxstore",
                "payments": [
                    {
                        "id": "D3DEECAB3C6C4B9EAF8EF4C1FE062FF3",
                        "paymentSystem": "6",
                        "paymentSystemName": "Boleto Bancário",
                        "value": 4450,
                        "installments": 1,
                        "referenceValue": 4450,
                        "cardHolder": None,
                        "firstDigits": None,
                        "lastDigits": None,
                        "url": "https://luxstore.vtexpayments.com.br:443/BankIssuedInvoice/Transaction/418213DE29634837A63DD693A937A696/Payment/D3DEECAB3C6C4B9EAF8EF4C1FE062FF3/Installment/{Installment}",
                        "giftCardId": None,
                        "giftCardName": None,
                        "giftCardCaption": None,
                        "redemptionCode": None,
                        "group": "bankInvoice",
                        "tid": None,
                        "dueDate": "2019-02-02",
                        "connectorResponses": {}
                    }
                ]
            }
        ]
    },
    "packageAttachment": {
        "packages": []
    },
    "sellers": [
        {
            "id": "1",
            "name": "Loja do Suporte",
            "logo": ""
        }
    ],
    "callCenterOperatorData": None,
    "followUpEmail": "7bf3a59bbc56402c810bda9521ba449e@ct.vtex.com.br",
    "lastMessage": None,
    "hostname": "luxstore",
    "invoiceData": None,
    "changesAttachment": {
        "id": "changeAttachment",
        "changesData": [
            {
                "reason": "Blah",
                "discountValue": 3290,
                "incrementValue": 0,
                "itemsAdded": [],
                "itemsRemoved": [
                    {
                        "id": "1234568358",
                        "name": "Bay Max L",
                        "quantity": 1,
                        "price": 3290,
                        "unitMultiplier": None
                    }
                ],
                "receipt": {
                    "date": "2019-02-06T20:46:04.4003606+00:00",
                    "orderId": "v5195004lux-01",
                    "receipt": "029f9ab8-751a-4b1e-bf81-7dd25d14b49b"
                }
            }
        ]
    },
    "openTextField": None,
    "roundingError": 0,
    "orderFormId": "caae7471333e403f959fa5fd66951340",
    "commercialConditionData": None,
    "isCompleted": True,
    "customData": None,
    "storePreferencesData": {
        "countryCode": "BRA",
        "currencyCode": "BRL",
        "currencyFormatInfo": {
            "CurrencyDecimalDigits": 2,
            "CurrencyDecimalSeparator": ",",
            "CurrencyGroupSeparator": ".",
            "CurrencyGroupSize": 3,
            "StartsWithCurrencySymbol": True
        },
        "currencyLocale": 1046,
        "currencySymbol": "R$",
        "timeZone": "E. South America Standard Time"
    },
    "allowCancellation": False,
    "allowEdition": False,
    "isCheckedIn": False,
    "marketplace": {
        "baseURL": "http://oms.vtexinternal.com.br/api/oms?an=luxstore",
        "isCertified": None,
        "name": "luxstore"
    },
    "authorizedDate": "2019-01-28T20:33:04.0000000+00:00",
    "invoicedDate": None
}

exemplo_get_order_filtrado = {}

exemplo_list_orders = {
    "list": [
        {
            "orderId": "v502559llux-01",
            "creationDate": "2019-02-04T10:29:11.0000000+00:00",
            "clientName": "J C",
            "items": None,
            "totalValue": 7453,
            "paymentNames": "Boleto Bancário",
            "status": "invoiced",
            "statusDescription": "Faturado",
            "marketPlaceOrderId": None,
            "sequence": "502559",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Sua Nota Fiscal foi emitida. Referente ao Pedido #v502559llux-01 Olá, J. Estamos empacotando seu produto para providenci",
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2019-02-07T21:29:54.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502556llux-01",
            "creationDate": "2019-01-28T20:09:43.0000000+00:00",
            "clientName": "Rodrigo VTEX",
            "items": None,
            "totalValue": 1160,
            "paymentNames": "Boleto Bancário",
            "status": "handling",
            "statusDescription": "Preparando Entrega",
            "marketPlaceOrderId": None,
            "sequence": "502556",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store Seu pedido foi alterado! Pedido realizado em: 28/01/2019 Olá, Rodrigo. Seu pedido foi alterado. Seguem informações abaixo: ",
            "ShippingEstimatedDate": "2019-02-04T20:33:46.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2019-01-28T20:33:04.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502553llux-01",
            "creationDate": "2019-01-24T12:35:19.0000000+00:00",
            "clientName": "test test",
            "items": None,
            "totalValue": 10150,
            "paymentNames": "Mastercard",
            "status": "ready-for-handling",
            "statusDescription": "Pronto para o manuseio",
            "marketPlaceOrderId": None,
            "sequence": "502554",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Sua Nota Fiscal foi emitida. Referente ao Pedido #v502553llux-01 Olá, test. Estamos empacotando seu produto para provide",
            "ShippingEstimatedDate": "2019-01-31T12:36:30.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2019-01-24T12:36:01.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502550llux-01",
            "creationDate": "2019-01-23T16:39:45.0000000+00:00",
            "clientName": "test test",
            "items": None,
            "totalValue": 10150,
            "paymentNames": "Mastercard",
            "status": "ready-for-handling",
            "statusDescription": "Pronto para o manuseio",
            "marketPlaceOrderId": None,
            "sequence": "502551",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Seu pagamento foi aprovado. Referente ao Pedido #v502550llux-01 Olá, test. Estamos providenciando a emissão da Nota Fisc",
            "ShippingEstimatedDate": "2019-01-30T16:40:55.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2019-01-23T16:40:27.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502547llux-01",
            "creationDate": "2019-01-23T16:34:20.0000000+00:00",
            "clientName": "test test",
            "items": None,
            "totalValue": 10150,
            "paymentNames": "Mastercard",
            "status": "ready-for-handling",
            "statusDescription": "Pronto para o manuseio",
            "marketPlaceOrderId": None,
            "sequence": "502548",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Seu pagamento foi aprovado. Referente ao Pedido #v502547llux-01 Olá, test. Estamos providenciando a emissão da Nota Fisc",
            "ShippingEstimatedDate": "2019-01-30T16:35:30.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2019-01-23T16:35:04.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502544llux-01",
            "creationDate": "2018-12-28T18:15:28.0000000+00:00",
            "clientName": "test test",
            "items": None,
            "totalValue": 8990,
            "paymentNames": "Boleto Bancário",
            "status": "canceled",
            "statusDescription": "Cancelado",
            "marketPlaceOrderId": None,
            "sequence": "502544",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Seu pedido foi cancelado. Referente ao Pedido #v502544llux-01 Resumo Itens R$ 89,90 Total R$ 89,90 Produto Alavanca De M",
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": None,
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502541llux-01",
            "creationDate": "2018-12-18T18:48:17.0000000+00:00",
            "clientName": "Douglas Rodrigues",
            "items": None,
            "totalValue": 3290,
            "paymentNames": "Boleto Bancário",
            "status": "canceled",
            "statusDescription": "Cancelado",
            "marketPlaceOrderId": None,
            "sequence": "502541",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Seu pedido foi cancelado. Referente ao Pedido #v502541llux-01 Resumo Itens R$ 32,90 Total R$ 32,90 Produto Bay Max L 1 u",
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": None,
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "v502538llux-01",
            "creationDate": "2018-12-12T18:21:47.0000000+00:00",
            "clientName": "test test",
            "items": None,
            "totalValue": 8990,
            "paymentNames": "Mastercard",
            "status": "ready-for-handling",
            "statusDescription": "Pronto para o manuseio",
            "marketPlaceOrderId": None,
            "sequence": "502538",
            "salesChannel": "1",
            "affiliateId": "",
            "origin": "Marketplace",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": " Lux Store 96 Seu pagamento foi aprovado. Referente ao Pedido #v502538llux-01 Olá, test. Estamos providenciando a emissão da Nota Fisc",
            "ShippingEstimatedDate": "2018-12-19T18:22:26.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-12-12T18:22:22.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "SCP-880102018018-01",
            "creationDate": "2018-11-30T17:34:01.0000000+00:00",
            "clientName": "roberta grecco",
            "items": None,
            "totalValue": 1250,
            "paymentNames": "",
            "status": "canceled",
            "statusDescription": "Cancelado",
            "marketPlaceOrderId": "880102018018-01",
            "sequence": "502537",
            "salesChannel": "1",
            "affiliateId": "SCP",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": "cancelamento teste shp ",
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-11-30T17:34:42.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "SCP-880091692043-01",
            "creationDate": "2018-11-30T17:28:35.0000000+00:00",
            "clientName": "roberta grecco",
            "items": None,
            "totalValue": 1250,
            "paymentNames": "",
            "status": "invoiced",
            "statusDescription": "Faturado",
            "marketPlaceOrderId": "880091692043-01",
            "sequence": "502536",
            "salesChannel": "1",
            "affiliateId": "SCP",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": None,
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-11-30T17:29:22.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "SCP-880091058221-01",
            "creationDate": "2018-11-30T17:18:00.0000000+00:00",
            "clientName": "roberta grecco",
            "items": None,
            "totalValue": 1250,
            "paymentNames": "",
            "status": "canceled",
            "statusDescription": "Cancelado",
            "marketPlaceOrderId": "880091058221-01",
            "sequence": "502535",
            "salesChannel": "1",
            "affiliateId": "SCP",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": "Teste de cancelamento do ShopFácil ",
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-11-30T17:18:44.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "SCP-880090643370-01",
            "creationDate": "2018-11-30T17:10:59.0000000+00:00",
            "clientName": "roberta grecco",
            "items": None,
            "totalValue": 1250,
            "paymentNames": "",
            "status": "ready-for-handling",
            "statusDescription": "Pronto para o manuseio",
            "marketPlaceOrderId": "880090643370-01",
            "sequence": "502534",
            "salesChannel": "1",
            "affiliateId": "SCP",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": None,
            "ShippingEstimatedDate": "2018-12-07T17:11:39.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-11-30T17:11:42.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "SCP-880090622238-01",
            "creationDate": "2018-11-30T17:10:45.0000000+00:00",
            "clientName": "roberta grecco",
            "items": None,
            "totalValue": 1250,
            "paymentNames": "",
            "status": "canceled",
            "statusDescription": "Cancelado",
            "marketPlaceOrderId": "880090622238-01",
            "sequence": "502533",
            "salesChannel": "1",
            "affiliateId": "SCP",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": None,
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": None,
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "MNC-877730530419-01",
            "creationDate": "2018-11-20T21:09:01.0000000+00:00",
            "clientName": "Carlos VTEX",
            "items": None,
            "totalValue": 11150,
            "paymentNames": "",
            "status": "canceled",
            "statusDescription": "Cancelado",
            "marketPlaceOrderId": "877730530419-01",
            "sequence": "502532",
            "salesChannel": "1",
            "affiliateId": "MNC",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": None,
            "ShippingEstimatedDate": None,
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-11-20T21:13:06.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        },
        {
            "orderId": "SCP-876733475998-01",
            "creationDate": "2018-11-16T16:58:18.0000000+00:00",
            "clientName": "roberta grecco",
            "items": None,
            "totalValue": 1250,
            "paymentNames": "",
            "status": "ready-for-handling",
            "statusDescription": "Pronto para o manuseio",
            "marketPlaceOrderId": "876733475998-01",
            "sequence": "502531",
            "salesChannel": "1",
            "affiliateId": "SCP",
            "origin": "Fulfillment",
            "workflowInErrorState": False,
            "workflowInRetry": False,
            "lastMessageUnread": None,
            "ShippingEstimatedDate": "2018-11-23T16:58:48.0000000+00:00",
            "ShippingEstimatedDateMax": None,
            "ShippingEstimatedDateMin": None,
            "orderIsComplete": True,
            "listId": None,
            "listType": None,
            "authorizedDate": "2018-11-16T16:58:53.0000000+00:00",
            "callCenterOperatorName": None,
            "totalItems": 1,
            "currencyCode": "BRL"
        }
    ],
    "facets": [],
    "paging": {
        "total": 84,
        "pages": 6,
        "currentPage": 1,
        "perPage": 15
    },
    "stats": {
        "stats": {
            "totalValue": {
                "Count": 84,
                "Max": 21526180,
                "Mean": 262672.75,
                "Min": 1160,
                "Missing": 0,
                "StdDev": 2348087.3869179883,
                "Sum": 22064511,
                "SumOfSquares": 463417439039853,
                "Facets": {
                    "origin": {
                        "Fulfillment": {
                            "Count": 68,
                            "Max": 11150,
                            "Mean": 1395.5882352941176,
                            "Min": 1250,
                            "Missing": 0,
                            "StdDev": 1200.5513439298484,
                            "Sum": 94900,
                            "SumOfSquares": 229010000,
                            "Facets": None
                        },
                        "Marketplace": {
                            "Count": 16,
                            "Max": 21526180,
                            "Mean": 1373100.6875,
                            "Min": 1160,
                            "Missing": 0,
                            "StdDev": 5374326.141087491,
                            "Sum": 21969611,
                            "SumOfSquares": 463417210029853,
                            "Facets": None
                        }
                    },
                    "currencyCode": {
                        "BRL": {
                            "Count": 84,
                            "Max": 21526180,
                            "Mean": 262672.75,
                            "Min": 1160,
                            "Missing": 0,
                            "StdDev": 2348087.3869179883,
                            "Sum": 22064511,
                            "SumOfSquares": 463417439039853,
                            "Facets": None
                        }
                    }
                }
            },
            "totalItems": {
                "Count": 84,
                "Max": 89,
                "Mean": 2.2261904761904763,
                "Min": 1,
                "Missing": 0,
                "StdDev": 9.660940100525016,
                "Sum": 187,
                "SumOfSquares": 8163,
                "Facets": {
                    "origin": {
                        "Fulfillment": {
                            "Count": 68,
                            "Max": 1,
                            "Mean": 1,
                            "Min": 1,
                            "Missing": 0,
                            "StdDev": 0,
                            "Sum": 68,
                            "SumOfSquares": 68,
                            "Facets": None
                        },
                        "Marketplace": {
                            "Count": 16,
                            "Max": 89,
                            "Mean": 7.4375,
                            "Min": 1,
                            "Missing": 0,
                            "StdDev": 21.92401651157926,
                            "Sum": 119,
                            "SumOfSquares": 8095,
                            "Facets": None
                        }
                    },
                    "currencyCode": {
                        "BRL": {
                            "Count": 84,
                            "Max": 89,
                            "Mean": 2.2261904761904763,
                            "Min": 1,
                            "Missing": 0,
                            "StdDev": 9.660940100525016,
                            "Sum": 187,
                            "SumOfSquares": 8163,
                            "Facets": None
                        }
                    }
                }
            }
        }
    }
}

exemplo_list_orders_filtrado = {}